name: GDL script file checker
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  example-job:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository to the runner
        uses: actions/checkout@v4 
      - name: Set execute permissions for script
        run: chmod +x scripts/check_gdl.sh
      - name: Run GDL script checking
        run: scripts/check_gdl.sh .
