name: GDL script file checker
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  example-job:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository to the runner
        uses: actions/checkout@v4

      - name: Install locales
        run: |
          sudo apt-get update && sudo apt-get install -y locales
          sudo locale-gen zh_CN.UTF-8
        env:
          LANG: zh_CN.UTF-8
          LANGUAGE: zh_CN:zh:en_US:en

      - name: Set execute permissions for script
        run: chmod +x ./scripts/check_gdl.sh

      - name: Download and extract sparrow-cli
        run: |
          mkdir -p $HOME/sparrow-cli
          curl -fL --retry 5 -o $HOME/sparrow-cli/sparrow-cli.tar.gz "https://github.com/codefuse-ai/CodeFuse-Query/releases/download/2.0.2/sparrow-cli-2.0.2.linux.tar.gz"
          tar -xzvf $HOME/sparrow-cli/sparrow-cli.tar.gz -C $HOME/sparrow-cli
          rm $HOME/sparrow-cli/sparrow-cli.tar.gz

      - name: Download and extract the latest sparrow-cli release
        run: |
          # Set up the name
          ASSET_NAME="sparrow-cli.linux.tar.gz"
      
          # Create the directory where the asset will be downloaded
          mkdir -p $HOME/sparrow-cli
      
          # Use GitHub API to get the latest release information
          RELEASE_INFO=$(curl -s -H "Authorization: token $GITHUB_TOKEN" "https://api.github.com/repos/codefuse-ai/CodeFuse-Query/releases/latest")
      
          # Extract the asset download URL for the asset name specified
          ASSET_URL=$(echo "$RELEASE_INFO" | jq --arg asset_name "$ASSET_NAME" -r '.assets[] | select(.name | contains($asset_name)).browser_download_url')
          echo "Downloading $ASSET_URL to $HOME/sparrow-cli/sparrow-cli.tar.gz"
      
          # Download and extract the asset in one line to avoid intermediate file
          curl -fL --retry 5 "$ASSET_URL" | tar -xz -C $HOME/sparrow-cli
        env:
          # The GitHub token is needed for API requests to avoid rate limits
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


      - name: Run GDL script checking
        run: ./scripts/check_gdl.sh .
        env:
          LC_ALL: zh_CN.UTF-8
